name: CI

on: [push, pull_request]

jobs:
  C_test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install C dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get remove needrestart
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Build C code
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run C tests
      run: |
        cd build
        make test

  Pylint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 mypy black

      - name: Check Python code formatting
        run: |
          black --check ./src/

      - name: Run Python linter
        run: |
          flake8 ./src/

      - name: Run python lint score
        run: |
          pylint ./src/

      - name: Run Python type checking
        run: |
          mypy ./src/
